---
- tags:
    - 'workstation'
    - 'workstation-base'
  block:
    # Enable 'classic' Snap support.
    # https://snapcraft.io/docs/installing-snap-on-fedora
    - name: 'configure snap'
      when: 'snap_enabled == true'
      ansible.builtin.file:
        src: '/var/lib/snapd/snap'
        dest: '/snap'
        state: 'link'
      tags:
        - 'snap'

    - name: 'install snap packages'
      when: 'snap_enabled == true'
      community.general.snap:
        name: '{{ item }}'
      become: true
      loop:
        - 'lnav'
      tags:
        - 'snap'
