---
- tags:
    - 'workstation'
    - 'workstation-base'
    - 'sudo'
  block:
    - name: 'configure sudo'
      ansible.builtin.copy:
        src: 'etc/sudoers.d/sam'
        dest: '/etc/sudoers.d/sam'
      tags:
        - docker
        - sudo
        - sudoers

    # - name: 'add user to docker group'
    #   ansible.builtin.user:
    #     name: '{{ lookup("env", "USER") }}'
    #     groups: 'docker'
    #     append: yes
    #   become: true
    #   tags:
    #     - 'never'
    #     - 'docker'
