---
snap_enabled: true
git_forges_local:
  - host: 'razz-berry.bunny-moth.ts.net'
    user: 'src'
    path: '~/Development/razz-berry.bunny-moth.ts.net/**'
    config: |
      [user]
      name = Sam Clements
      email = sam@borntyping.co.uk
      [core]
      sshCommand = ssh -i '~/.ssh/keys/id_ed25519_gitlab_src'
