---
collections:
  - name: 'ansible.posix'
    version: '*'
  - name: 'community.crypto'
    version: '*'
  - name: 'community.general'
    version: '*'
  - name: 'community.postgresql'
    version: '*'
