---
- tags: ['brew', 'homebrew']
  block:
    - ansible.builtin.include_role:
        name: 'base/linuxbrew'

    - name: 'brew : install brew packages'
      tags: ['direnv', 'fzf', 'go', 'starship', 'zoxide']
      community.general.homebrew:
        state: 'present'
        name:
          - 'direnv'
          - 'fzf'
          - 'go'
          - 'starship'
          - 'zoxide'
