---
- tags: ['docker']
  block:
    - name: 'install docker packages for fedora'
      when: 'ansible_distribution == "Fedora"'
      include_tasks: 'fedora/main.yml'

    - name: 'install docker packages for debian'
      tags: ['apt', 'debian', 'syncthing', 'tailscale']
      when: 'ansible_os_family == "Debian"'
      include_tasks: 'debian/main.yml'

    # Run "newgrp docker" to use the new group without logging out and back in.
    - name: 'add user to docker group ({{ ansible_user_id }})'
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        groups: 'docker'
        append: true

    - name: 'start and enable docker services'
      tags: ['systemd']
      become: true
      ansible.builtin.systemd_service:
        name: 'docker.service'
        scope: 'system'
        state: 'started'
        enabled: true
