---
- tags: ['packages']
  block:
    - name: 'install fedora packages'
      when: 'ansible_os_family == "RedHat"'
      include_tasks: 'redhat/main.yml'

    - name: 'install debian packages'
      tags: ['apt', 'debian', 'syncthing', 'tailscale']
      when: 'ansible_os_family == "Debian"'
      include_tasks: 'debian/main.yml'

    - import_tasks: 'common.yml'

    - name: 'install snap packages'
      when: 'ansible_distribution in ("Fedora", "Ubuntu")'
      include_tasks: 'snap.yml'
