---
- tags: ['packages']
  block:
    - name: 'install base packages for fedora'
      when: 'ansible_os_family == "RedHat"'
      include_tasks: 'redhat/main.yml'

    - name: 'install base packages for debian'
      tags: ['apt', 'debian', 'syncthing', 'tailscale']
      when: 'ansible_os_family == "Debian"'
      include_tasks: 'debian/main.yml'

    - import_tasks: 'common.yml'
