---
- tags: ['base', 'packages']
  block:
    - name: 'install fedora packages'
      include_tasks: 'redhat/main.yml'
      when: 'ansible_os_family == "RedHat"'

    - name: 'install debian packages'
      include_tasks: 'debian/main.yml'
      when: 'ansible_os_family == "Debian"'

    - import_tasks: 'common.yml'

    - name: 'install snap packages'
      include_tasks: 'snap.yml'
      when: 'ansible_distribution in ("Fedora", "Ubuntu")'
