---
- tags: ['apt', 'base', 'ubuntu']
  block:
    - name: 'ubuntu : add git ppa'
      become: true
      ansible.builtin.apt_repository:
        repo: 'ppa:git-core/ppa'

    - name: 'ubuntu : install apt packages'
      become: true
      ansible.builtin.apt:
        state: 'latest'
        pkg:
          - 'build-essential'
          - 'gcc'
          - 'python3'
          - 'python3-pip'
          - 'sqlite'
          - 'zsh-doc'

    - name: 'ubuntu : remove apt packages'
      become: true
      ansible.builtin.apt:
        state: 'absent'
        pkg:
          - 'ansible-core'
          - 'direnv'

- tags: ['base', 'brew', 'homebrew']
  block:
    - name: 'ubuntu : check homebrew executable'
      stat:
        path: '/home/linuxbrew/.linuxbrew/bin/brew'
      register: 'homebrew_executable'
      check_mode: true

    - name: 'ubuntu : create homebrew config directory'
      when: 'homebrew_executable.stat.exists'
      ansible.builtin.file:
        name: '/home/linuxbrew/.linuxbrew/etc/homebrew'
        state: 'directory'

    - name: 'ubuntu : create homebrew config'
      when: 'homebrew_executable.stat.exists'
      ansible.builtin.copy:
        src: 'brew.env'
        dest: '/home/linuxbrew/.linuxbrew/etc/homebrew/brew.env'

    - name: 'ubuntu : install homebrew packages'
      when: 'homebrew_executable.stat.exists'
      tags:
        - 'direnv'
        - 'go'
        - 'starship'
        - 'zoxide'
      community.general.homebrew:
        state: 'present'
        name:
          - 'direnv'
          - 'go'
          - 'starship'
          - 'zoxide'
