---
- tags: ['apt', 'base', 'debian']
  block:
    - name: 'debian : install tailscale repo key'
      tags: ['tailscale']
      become: true
      ansible.builtin.get_url:
        url: 'https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg'
        dest: '/usr/share/keyrings/tailscale-archive-keyring.gpg'

    - name: 'debian : install tailscale repo'
      tags: ['tailscale']
      become: true
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main'
        state: 'present'
