---
- tags: ['snap']
  block:
    # Enable 'classic' Snap support.
    # https://snapcraft.io/docs/installing-snap-on-fedora
    - name: 'snap : configure'
      when: 'ansible_distribution == "Fedora"'
      become: true
      ansible.builtin.file:
        src: '/var/lib/snapd/snap'
        dest: '/snap'
        state: 'link'

    - name: 'snap : install packages'
      become: true
      community.general.snap:
        name: '{{ item }}'
      loop:
        - 'dart-sass'
        - 'lnav'
