---
- tags: apt
  block:
    - name: configure apt repository keys
      apt_key:
        id: '{{ item }}'
        keyserver: 'hkp://keyserver.ubuntu.com:80'
      register: apt_repositories_key
      become: 'yes'
      with_list:
        - '0EBFCD88'  # docker
        - 'E1DF1F24'  # git

    - name: configure apt repositories
      apt_repository:
        repo: '{{ item }}'
        state: present
      register: apt_repositories
      become: 'yes'
      with_items:
        - 'deb [ arch=amd64 ] https://download.docker.com/linux/ubuntu bionic stable'
        - 'deb http://ppa.launchpad.net/git-core/ppa/ubuntu cosmic main'
        - 'deb https://packagecloud.io/github/git-lfs/ubuntu/ bionic main'

    - name: update apt repositories
      apt:
        update_cache: 'yes'
      when: apt_repositories.changed or apt_repositories_key.changed
      become: 'yes'
