---
- name: 'configure repository keys'
  apt_key:
    id: '{{ item }}'
    keyserver: 'hkp://keyserver.ubuntu.com:80'
  register: apt_repositories_key
  become: 'yes'
  with_list:
    - 0F833EAD  # asciinema
    - 58118E89F3A912897C070ADBF76221572C52609D  # docker
    - E1DF1F24  # git

- name: 'configure repositories'
  apt_repository:
    repo: '{{ item }}'
    state: present
  register: apt_repositories
  become: 'yes'
  with_items:
    - deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main
    - deb http://ppa.launchpad.net/zanchey/asciinema/ubuntu trusty main
    - deb https://apt.dockerproject.org/repo ubuntu-xenial main
    - deb https://packagecloud.io/github/git-lfs/ubuntu/ trusty main

- name: 'update repositories'
  apt: update_cache=yes
  when: apt_repositories.changed or apt_repositories_key.changed
  become: 'yes'
