#
# Install docker
#
# keyserver=hkp://pgp.mit.edu:80

- name: docker | install
  apt: 'pkg={{ item }} state=latest'
  become: yes
  with_items:
    - docker-engine
    - apparmor
    - cgroup-lite

- name: docker | create group
  group:
    name: docker
    state: present
  become: yes

- name: docker | add user to docker group
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: true
  become: yes
