#!/bin/bash

# https://gist.github.com/davejamesmiller/1965569
ask () {
    while true; do
        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question
        read -p "$1 [$prompt] " REPLY

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

if [ -z "$1" ]; then
    echo "usage: git tag-version <version> [<commit>]"
    exit
fi

echo "Tagging version $1 (git tag -a \"v$1\" -m \"Version $1\" ${2:-HEAD})"
if ask "Has the package's version number been modified?" Y; then
    git tag -a "v$1" -m "Version $1" "${2:-HEAD}"
else
    exit 1
fi

echo "Pushing commits and tags (git push --follow-tags)"
if ask "Should the new commits and tags be pushed?" Y; then
    git push --follow-tags
else
    exit 1
fi
