---
- tags:
    - 'cargo'
    - 'rust'
  block:
    - name: 'install difftastic'
      ansible.builtin.command: 'cargo install difftastic'
      creates: '{{ lookup("env", "HOME") }}/.cargo/bin/difft'
