#
# Install local gems
#

- name: install ruby packages
  gem:
    state: latest
    name: '{{ item }}'
    executable: gem2.3
    user_install: yes
  with_items:
    - bundler
    - fpm
    - ruby-graphviz
    - travis
    - travis-lint

- name: bundle | directory
  file:
    name: '{{ ansible_env.HOME }}/.bundle'
    state: directory
  tags:
    - dotfiles
    - bundle

- name: bundle | config
  template:
    src: bundle_config
    dest: '{{ ansible_env.HOME }}/.bundle/config'
  tags:
    - dotfiles
    - bundle
