---
- name: 'ruby : install'
  gem:
    state: latest
    name: '{{ item }}'
    executable: gem2.5
    user_install: 'yes'
  with_items:
    - bundler
    - fpm
    - rake
    - rubocop
    - ruby-graphviz
    - travis
    - travis-lint

- name: 'ruby : create ~/.bundle'
  file:
    name: '{{ ansible_env.HOME }}/.bundle'
    state: directory
  tags:
    - dotfiles
    - bundle

- name: 'ruby : create ~/.bundle/config'
  template:
    src: bundle_config
    dest: '{{ ansible_env.HOME }}/.bundle/config'
  tags:
    - dotfiles
    - bundle
