---
- tags:
    - 'cargo'
    - 'rust'
  block:
    - name: 'install cargo packages'
      ansible.builtin.command: 'cargo install {{ item.package }}'
      args:
        creates: '{{ lookup("env", "HOME") }}/.cargo/bin/{{ item.bin|default(item.package) }}'
      loop:
        - package: atuin
          