---
- tags:
    - 'cargo'
    - 'rust'
  block:
    - name: 'install cargo packages'
      ansible.builtin.command: >-
        cargo install --force
        bat
        difftastic
        exa
        ripgrep
        sd
