---
- tags:
    - 'ssh'
  block:
    - name: 'create ssh directory'
      ansible.builtin.file:
        name: '{{ lookup("env", "HOME") }}/.ssh'
        state: 'directory'

    - name: 'create ssh sub-directories'
      ansible.builtin.file:
        name: '{{ lookup("env", "HOME") }}/.ssh/{{ item }}'
        state: 'directory'
      with_items:
        - 'config.d'
        - 'hosts'
        - 'keys'
        - 'controlmasters'

    - name: 'create ssh fragments'
      ansible.builtin.copy:
        src: '.ssh/config.d/'
        dest: '{{ lookup("env", "HOME") }}/.ssh/config.d/'

    - name: 'generate essential ssh keys'
      community.crypto.openssh_keypair:
        type: 'ed25519'
        path: '{{ lookup("env", "HOME") }}/.ssh/keys/id_ed25519_{{ item }}'
        comment: '{{ lookup("env", "HOST") }}'
      loop:
        - github_borntyping
        - github_borntyping_corporate
        - gitlab

    - name: 'generate configured ssh keys'
      community.crypto.openssh_keypair:
        type: 'ed25519'
        path: '{{ lookup("env", "HOME") }}/.ssh/keys/id_ed25519_{{ item }}'
        comment: '{{ lookup("env", "HOST") }}'
      loop: '{{ ssh_key_names }}'

    - name: 'assemble ssh config'
      ansible.builtin.assemble:
        src: '{{ lookup("env", "HOME") }}/.ssh/config.d/'
        dest: '{{ lookup("env", "HOME") }}/.ssh/config'
        delimiter: '\n'
