---
- tags: micro
  block:
    - name: create micro configuration directory
      file:
        name: '{{ lookup("env", "HOME") }}/.config/micro'
        state: directory

    - name: create micro configuration
      copy:
        src: 'config/micro/settings.json'
        dest: '{{ lookup("env", "HOME") }}/.config/micro/settings.json'
