- name: ssh | create ~/.ssh directory
  file: 'name={{ ansible_env.HOME }}/.ssh state=directory'

- name: ssh | create ~/.ssh/config.d directory
  file: 'name={{ ansible_env.HOME }}/.ssh/config.d state=directory'

- name: ssh | create ~/.ssh/config
  shell: "cat {{ ansible_env.HOME }}/.ssh/config.d/*.config > ~/.ssh/config"

# - name: ssh | generate ssh key
#   user: 'name={{ ansible_env.USER }} generate_ssh_key=true'
