---
- name: 'blink1 : turn on at 9AM'
  cron:
    name: 'enable blink(1)'
    hour: 9
    minute: 0
    job: /home/sam/.local/bin/blink1-tool --id all --off

- name: 'blink1 : turn off at 6PM'
  cron:
    name: 'disable blink(1)'
    hour: 18
    minute: 0
    job: /home/sam/.local/bin/blink1-tool --id all --off
