---
- tags: micro
  block:
    - name: create micro configuration directory
      file:
        name: '{{ ansible_env.HOME }}/.config/micro'
        state: directory

    - name: create micro configuration
      copy:
        src: 'config/micro/settings.json'
        dest: '{{ ansible_env.HOME }}/.config/micro/settings.json'
