---
- tags: 'micro'
  block:
    - name: 'create micro configuration directory'
      ansible.builtin.file:
        name: '{{ lookup("env", "HOME") }}/.config/micro'
        state: 'directory'

    - name: 'create micro configuration'
      ansible.builtin.copy:
        src: '.config/micro/settings.json'
        dest: '{{ lookup("env", "HOME") }}/.config/micro/settings.json'
