---
- tags: ssh
  block:
    - name: create ssh directory
      file:
        name: '{{ lookup("env", "HOME") }}/.ssh'
        state: directory

    - name: create ssh sub-directories
      file:
        name: '{{ lookup("env", "HOME") }}/.ssh/{{ item }}'
        state: directory
      with_items:
        - config.d
        - hosts
        - keys

    - name: create ssh fragments
      copy:
        src: 'ssh/config.d/'
        dest: '{{ lookup("env", "HOME") }}/.ssh/config.d/'
      notify: ssh

    - meta: flush_handlers
