---
- name: 'generic workstation packages'
  tags: ['apt', 'base', 'dnf']
  block:
    - name: 'install workstation packages'
      become: true
      ansible.builtin.package:
        state: 'latest'
        pkg:
          - 'gitg'
          - 'plantuml'
