---
- tags: ['workstation']
  block:
    - name: 'install workstation packages with dnf'
      tags: ['dnf']
      when: 'ansible_os_family == "RedHat"'
      import_tasks: 'redhat/main.yml'

    - name: 'install workstation packages with apt'
      tags: ['apt']
      when: 'ansible_os_family == "Debian"'
      import_tasks: 'debian/main.yml'

    - name: 'install workstation packages'
      tags: ['apt', 'dnf', 'package']
      when: 'ansible_distribution in ["Fedora", "Ubuntu"]'
      import_tasks: 'common.yml'

    - name: 'install workstation packages with snap'
      tags: ['snap']
      when: 'ansible_distribution in ["Fedora", "Ubuntu"]'
      import_tasks: 'snap.yml'
