---
- name: common
  hosts:
   - umbreon
   - razz-berry
  roles:
    - role: base
    - role: ssh
    - role: git
    - role: zsh

- name: workstation
  hosts:
    - umbreon
  roles:
    - role: home
    - role: workstation

- name: server
  hosts:
    - razz-berry
  roles:
    - role: web
