---
- name: 'base'
  hosts: 'src'
  roles:
    - role: 'base/packages'
    - role: 'base/tailscale'
    - role: 'base/cockpit'

- name: 'home'
  hosts: 'src'
  roles:
    - role: 'home/bin'
    - role: 'home/cfg'
    - role: 'home/git'
    - role: 'home/ssh'
    - role: 'home/zsh'

- name: 'workstation'
  hosts: 'workstation'
  roles:
    - role: 'workstation'

- name: 'webserver'
  hosts: 'webserver'
  roles:
    - role: 'webserver/foundryvtt'
      tags: 'webserver'
