---
- name: 'common'
  hosts:
    - 'umbreon'
    - 'razz-berry'
  roles:
    - role: 'tailscale'
    - role: 'base'
    - role: 'home'
    - role: 'ssh'
    - role: 'git'
    - role: 'zsh'

- name: 'workstation'
  hosts:
    - 'umbreon'
  roles:
    - role: 'workstation'

- name: 'server'
  hosts:
    - 'razz-berry'
  roles:
    - role: 'web'
