---
- name: 'base'
  hosts: 'src'
  roles:
    - {tags: 'base', role: 'base/packages'}
    - {tags: 'base', role: 'base/tailscale'}
    - {tags: 'base', role: 'base/cockpit'}
    - {tags: 'base', role: 'base/docker'}
    - {tags: 'base', role: 'base/ufw'}

- name: 'home'
  hosts: 'src'
  roles:
    - {tags: 'home', role: 'home/bin'}
    - {tags: 'home', role: 'home/cfg'}
    - {tags: 'home', role: 'home/git'}
    - {tags: 'home', role: 'home/ssh'}
    - {tags: 'home', role: 'home/zsh'}
    - {tags: 'home', role: 'home/syncthing'}

- name: 'workstation'
  hosts: 'workstation'
  roles:
    - {tags: 'workstation', role: 'workstation'}

- name: 'webserver'
  hosts: 'webserver'
  roles:
    - {tags: 'webserver', role: 'webserver/base'}
    - {tags: 'webserver', role: 'webserver/foundryvtt'}
