#!/bin/zsh

export ZSH_DIRECTORY="$"

source "$HOME/.local/share/zsh/lib/aliases.zsh"
source "$HOME/.local/share/zsh/lib/completion.zsh"
source "$HOME/.local/share/zsh/lib/environment.zsh"
source "$HOME/.local/share/zsh/lib/history.zsh"
source "$HOME/.local/share/zsh/lib/prompt.zsh"
source "$HOME/.local/share/zsh/lib/syntax-highlighting.zsh"
source "$HOME/.local/share/zsh/lib/virtualenvwrapper.zsh"

