---
- tags: ['bin']
  block:
    - name: 'install executables into ~/.local/bin'
      tags:
        - 'local'
        - 'bin'
        - 'atuin'
        - 'aws-vault'
        - 'just'
        - 'kubectx'
        - 'kubens'
        - 'starship'
      copy:
        src: '{{ ansible_architecture }}/.local/bin/'
        dest: '{{ ansible_user_dir }}/.local/bin'
        mode: '0755'

    - name: 'install scripts into ~/.local/bin'
      tags:
        - 'local'
        - 'bin'
        - 'git-fixup'
      copy:
        src: '.local/bin/'
        dest: '{{ ansible_user_dir }}/.local/bin'
        mode: '0755'
      diff: false

    - name: 'install python packages with pipx'
      tags:
        - 'python'
        - 'pipx'
      community.general.pipx:
        name: '{{ item }}'
      loop:
        - 'poetry'
        - 'switchbox'

#    - name: 'install golang executables'
#      ansible.builtin.command: 'go install {{ item.package }}'
#      args:
#        creates: '{{ ansible_user_dir }}/.local/lib/go/bin/{{ item.bin }}'
#      environment:
#        GOPATH: '{{ ansible_user_dir }}/.local/lib/go'
#      loop:
#        - package: 'github.com/stern/stern@latest'
#          bin: 'stern'
#        - package: 'github.com/bbrks/shotgun@latest'
#          bin: 'shotgun'
#      tags:
#        - 'golang'
#        - 'never'
