---
- tags:
    - 'home'
    - 'cfg'
  block:
    - name: 'set facts'
      tags: ['always', 'scripts']
      ansible.builtin.set_fact:
        _cfg_scripts: '{{ cfg_scripts + cfg_scripts_local + cfg_scripts_secret }}'

    - name: 'copy dotfiles'
      copy:
        src: '{{ item }}'
        dest: '{{ ansible_user_dir }}/.{{ item }}'
      with_items:
        - 'ackrc'
        - 'inputrc'
        - 'multitailrc'
      tags:
        - 'dotfiles'

    - name: 'create ~/.bin directory'
      tags: ['bin']
      ansible.builtin.file:
        name: '{{ ansible_user_dir }}/.bin'
        state: 'directory'

    - name: 'install scripts from ansible variables into ~/.bin'
      tags: ['bin', 'scripts']
      ansible.builtin.copy:
        content: '{{ item.content }}'
        dest: '{{ ansible_user_dir }}/.bin/{{ item.name }}'
        mode: '0755'
      loop: '{{ _cfg_scripts }}'
      loop_control:
        label: '{{ item.name }}'

    - name: 'install scripts from ansible source into ~/.local/bin (ubuntu only)'
      when: 'ansible_os_family == "Debian"'
      tags: ['local', 'bin', 'scripts']
      copy:
        src: 'ubuntu/.local/bin/'
        dest: '{{ ansible_user_dir }}/.local/bin'
        mode: '0755'

    - name: 'install scripts from ansible source into ~/.local/share/src'
      tags: ['local', 'share', 'src', 'git', 'scripts']
      ansible.builtin.copy:
        src: '.local/share/src/'
        dest: '{{ ansible_user_dir }}/.local/share/src/'
        mode: '0755'

    - name: 'install man pages into ~/.local/share/man'
      tags: ['local', 'share', 'man']
      ansible.builtin.copy:
        src: '.local/share/man/'
        dest: '{{ ansible_user_dir }}/.local/share/man/'
        mode: '0755'

    - name: 'enable user podman socket'
      ansible.builtin.systemd:
        name: 'podman.socket'
        state: 'started'
        scope: 'user'
      when: 'ansible_distribution == "Fedora"'
      tags:
        - 'fedora'
        - 'podman'
        - 'socket'
        - 'systemd'

    - name: 'copy config directory into ~/.config'
      ansible.builtin.copy:
        src: '.config/{{ item }}/'
        dest: '{{ ansible_user_dir }}/.config/{{ item }}/'
      loop:
        - 'atuin'
        - 'direnv'
        - 'fish'
        - 'htop'
        - 'micro'
        - 'pip'
        - 'pypoetry'
        - 'tmux'
      tags:
        - 'config'
        - 'python'

        - 'atuin'
        - 'direnv'
        - 'fish'
        - 'htop'
        - 'micro'
        - 'pip'
        - 'poetry'
        - 'tmux'
