---
- tags:
    - 'workstation'
    - 'workstation-home'
  block:
    - name: 'install .fonts/'
      copy:
        src: 'home/.fonts/'
        dest: '{{ lookup("env", "HOME") }}/.fonts'
      tags:
        - 'config'
        - 'fonts'

    - name: 'install .config/tilix/'
      copy:
        src: 'home/.config/tilix/'
        dest: '{{ lookup("env", "HOME") }}/.config/tilix'
      tags:
        - 'config'
        - 'tilix'
