---
- tags:
    - 'workstation'
    - 'workstation-home'
  block:
    - name: 'install .fonts/'
      ansible.builtin.copy:
        src: '.fonts/'
        dest: '{{ ansible_user_dir }}/.fonts'
      tags:
        - 'fonts'

    - name: 'install .config/tilix/'
      ansible.builtin.copy:
        src: '.config/tilix/'
        dest: '{{ ansible_user_dir }}/.config/tilix'
      tags:
        - 'config'
        - 'tilix'
