#
# Configure APT repos in one place, then update metadata.
#

- name: 'configure repositories'
  apt_repository: >
    repo='{{ item }}'
    state=present
  become: yes
  with_items:
    - 'deb http://repository.spotify.com stable non-free'
    - 'deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main'

- name: 'configure repository keys'
  apt_key: "id={{ item }} keyserver=hkp://keyserver.ubuntu.com:80"
  become: yes
  with_items:
    - 'D2C19886' # spotify
    - 'D59097AB' # slack

- name: 'update repositories'
  apt: 'update_cache=yes'
  become: yes
