---
- tags:
    - 'workstation'
    - 'graphical'
  block:
    - name: 'add 1Password repository key'
      ansible.builtin.rpm_key:
        key: 'https://downloads.1password.com/linux/keys/1password.asc'
        state: 'present'
      become: 'yes'
      tags:
       - 'rpm'
       - 'dnf'
       - '1p'

    - name: 'add 1Password repository'
      ansible.builtin.yum_repository:
        name: '1password'
        description: '1Password Stable Channel'
        baseurl: 'https://downloads.1password.com/linux/rpm/stable/$basearch'
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: 'https://downloads.1password.com/linux/keys/1password.asc'
      become: 'yes'
      tags:
       - 'dnf'
       - '1p'

    - name: 'install packages'
      ansible.builtin.dnf:
        name:
          - '1password'
          - 'firefox'
          - 'git-cola'
          - 'gitg'
          - 'gnome-shell-extension-dash-to-dock'
          - 'gnome-tweaks'
          - 'google-chrome-stable'
          - 'meld'
          - 'tilix'
          - 'zeal'
        state: 'latest'
      become: 'yes'
      tags:
        - 'dnf'
        - '1p'

    - name: 'install snap packages'
      when: 'snap_enabled == true'
      community.general.snap:
        name: '{{ item }}'
      become: 'yes'
      loop:
        - 'slack'
      tags:
        - 'snap'

    - name: 'install snap packages with --classic'
      when: 'snap_enabled == true'
      community.general.snap:
        name: '{{ item }}'
        classic: true
      become: 'yes'
      loop:
        - 'code'
        - 'pycharm-professional'
      tags:
        - 'snap'
        - 'vscode'
