---
- tags:
    - 'workstation'
    - 'hardware'
  block:
    # Configure immediately by running this as root:
    # $ echo 2 >> /sys/module/hid_apple/parameters/fnmode
    - name: 'configure varmilo keyboard'
      ansible.builtin.copy:
        src: 'etc/modprobe.d/hid_apple.conf'
        dest: '/etc/modprobe.d/hid_apple.conf'
      tags:
        - 'never'
        - 'hardware'
