---
- name: 'ubuntu workstation packages'
  tags: ['workstation', 'ubuntu']
  block:
    - name: 'install apt packages'
      become: true
      ansible.builtin.apt:
        state: 'latest'
        pkg:
          - 'meld'
          - 'gitg'
