---
- name: 'fedora workstation packages'
  tags: ['workstation', 'dnf']
  block:
    - name: 'add 1Password repository key'
      ansible.builtin.rpm_key:
        key: 'https://downloads.1password.com/linux/keys/1password.asc'
        state: 'present'
      become: 'yes'
      tags:
        - 'rpm'
        - 'dnf'
        - '1p'

    - name: 'add 1Password repository'
      ansible.builtin.yum_repository:
        name: '1password'
        description: '1Password Stable Channel'
        baseurl: 'https://downloads.1password.com/linux/rpm/stable/$basearch'
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: 'https://downloads.1password.com/linux/keys/1password.asc'
      become: 'yes'
      tags:
        - 'dnf'
        - '1p'

    - name: 'install developer workstation packages with dnf'
      tags: ['fzf', 'postgres']
      become: true
      ansible.builtin.dnf:
        state: 'latest'
        pkg:
          - 'ShellCheck'
          - 'ansible-core'
          - 'awscli2'
          - 'cargo'
          - 'clippy'
          - 'cockpit'
          - 'gcc-c++'
          - 'golang'
          - 'npm'
          - 'podman'
          - 'postgresql'
          - 'postgresql-server'
          - 'postgresql-upgrade'
          - 'python3'
          - 'python3-black'
          - 'python3-devel'
          - 'python3-flake8'
          - 'python3-mypy'
          - 'python3-pip'
          - 'python3-psycopg2'
          - 'python3-psycopg3'
          - 'python3-pytest'
          - 'python3.10'
          - 'python3.11'
          - 'python3.12'
          - 'python3.13'
          - 'python3.8'
          - 'python3.9'
          - 'rust-src'
          - 'rustc'
          - 'rustfmt'
          - 'snapd'
          - 'sqlite'
          - 'util-linux-user'
          - 'yamllint'

    - name: 'install graphical workstation packages with dnf'
      ansible.builtin.dnf:
        name:
          - '1password'
          - 'firefox'
          - 'git-cola'
          - 'gitg'
          - 'gnome-shell-extension-dash-to-dock'
          - 'gnome-tweaks'
          - 'google-chrome-stable'
          - 'meld'
          - 'tilix'
          - 'zeal'
        state: 'latest'
      become: 'yes'
      tags:
        - 'dnf'
        - '1p'
