#
# Fetch {{ url }} and use it to install {{ name }}.
#

- name: "{{ name }} : version {{ version }}"
  set_fact: "deb_version={{ version }}"

- name: "{{ name }} : query"
  command: "dpkg -s {{ name }}"
  register: "deb_dpkg"
  failed_when: "deb_dpkg.rc > 1"
  changed_when: no

- name: "{{ name }} : installed?"
  set_fact: >
    deb_install='{{
      (not deb_dpkg.get('skipped', False)) and
      deb_dpkg.rc == 1
    }}'

- name: "{{ name }} : outdated?"
  set_fact: >
    deb_update='{{
      (not deb_dpkg.get('skipped', False)) and
      deb_dpkg.rc == 0 and
      "Version: %s" % deb_version not in deb_dpkg.stdout
    }}'

- name: "{{ name }} : fetch"
  get_url:
    url: "{{ url }}"
    dest: "/tmp/{{ url | basename }}"
    validate_certs: "{{ validate_certs|default('true') }}"
  when: "deb_install or deb_update"

- name: "{{ name }} : install"
  apt:
    deb: "/tmp/{{ url | basename }}"
  become: yes
  when: "deb_install or deb_update"
