#!/usr/bin/env python3.11
# pip install --user tabulate

import json
import sys

import tabulate

for line in sys.stdin:
    if line:
        data = json.loads(line)
        table = [[k, v] for k, v in data.items()]
        print(tabulate.tabulate(table, tablefmt="plain"))
