---
dependencies:
  - role: stage2-user
    tags: stage2
  - role: deb
    name: atom
    version: 1.16.0
    url: https://github.com/atom/atom/releases/download/v1.16.0/atom-amd64.deb
    tags: atom
