#!/bin/bash

set -euo pipefail

git fetch --all

# Remove references deleted from the remotes.
git remote | xargs --no-run-if-empty --max-args=1 -- bash -c 'git remote prune "$@"; echo "Pruned remote $@"' _

# Remove branches that have been merged into 'main' or 'master'.
git for-each-ref --format '%(refname:short)' refs/heads/ |
  grep -e 'master' -e 'main' |
  xargs --no-run-if-empty --max-args=1 -- git branch --merged |
  grep -v -e 'master' -e 'main' -e '\* ' |
  sort |
  uniq |
  xargs --no-run-if-empty --max-args=1 -- git branch -d
