---
- tags:
    - 'home'
  block:
    - name: 'copy dotfiles'
      copy:
        src: '{{ item }}'
        dest: '{{ ansible_user_dir }}/.{{ item }}'
      with_items:
        - 'ackrc'
        - 'htoprc'
        - 'inputrc'
        - 'multitailrc'
      tags:
        - 'dotfiles'
        - 'multitailrc'

    # Use the 'bin' role for architecture-dependant executables.
    - name: 'install scripts into ~/.local/bin'
      tags: [local, bin]
      copy:
        src: '.local/bin/'
        dest: '{{ ansible_user_dir }}/.local/bin'
        mode: '0755'

    - name: 'create ~/.bin directory'
      tags: [bin]
      ansible.builtin.file:
        name: '{{ ansible_user_dir }}/.bin'
        state: 'directory'

    - name: 'install scripts from ansible variables into ~/.bin'
      tags: [bin]
      ansible.builtin.copy:
        content: '{{ item.value }}'
        dest: '{{ ansible_user_dir }}/.bin/{{ item.key }}'
        mode: '0755'
      loop: '{{ bin_scripts|combine(bin_scripts_local)|dict2items }}'
      loop_control:
        label: '{{ item.key }}'

    - name: 'install scripts from ansible source into ~/.local/share/src'
      tags: [local, share, src]
      ansible.builtin.copy:
        src: '.local/share/src/'
        dest: '{{ ansible_user_dir }}/.local/share/src/'
        mode: '0755'

    - name: 'install man pages into ~/.local/share/man'
      tags: [local, share, man]
      ansible.builtin.copy:
        src: '.local/share/man/'
        dest: '{{ ansible_user_dir }}/.local/share/man/'
        mode: '0755'

    - name: 'enable user podman socket'
      ansible.builtin.systemd:
        name: 'podman.socket'
        state: 'started'
        scope: user
      when: 'ansible_distribution == "Fedora"'
      tags:
        - 'fedora'
        - 'podman'
        - 'socket'
        - 'systemd'

    - name: 'copy config directory into ~/.config'
      ansible.builtin.copy:
        src: '.config/{{ item }}/'
        dest: '{{ ansible_user_dir }}/.config/{{ item }}/'
      loop:
        - atuin
        - direnv
        - fish
        - micro
        - pip
        - pypoetry
      tags:
        - atuin
        - config
        - direnv
        - fish
        - micro
        - pip
        - poetry
        - python

    - name: 'copy config files into ~/.config'
      ansible.builtin.copy:
        src: '.config/{{ item }}'
        dest: '{{ ansible_user_dir }}/.config/{{ item }}'
      loop:
        - starship.toml
      tags:
        - starship

    - name: 'install python packages with pipx'
      community.general.pipx:
        name: '{{ item }}'
      loop:
        - 'poetry'
        - 'switchbox'
      tags:
        - 'python'
        - 'pipx'

#    - name: 'install golang executables'
#      ansible.builtin.command: 'go install {{ item.package }}'
#      args:
#        creates: '{{ ansible_user_dir }}/.local/lib/go/bin/{{ item.bin }}'
#      environment:
#        GOPATH: '{{ ansible_user_dir }}/.local/lib/go'
#      loop:
#        - package: github.com/stern/stern@latest
#          bin: stern
#        - package: github.com/bbrks/shotgun@latest
#          bin: shotgun
#      tags:
#        - 'bin'
#        - 'golang'
