---
- tags:
    - tailscale
  block:
    - name: "add tailscale repository"
      become: true
      ansible.builtin.yum_repository:
        name: "tailscale"
        description: "Tailscale stable"
        baseurl: "https://pkgs.tailscale.com/stable/fedora/$basearch"
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: "https://pkgs.tailscale.com/stable/fedora/repo.gpg"

    - name: 'install tailscale package'
      become: true
      ansible.builtin.dnf:
        state: 'latest'
        pkg:
          - 'tailscale'

    - name: "create certificates"
      tags: [certificates]
      become: true
      ansible.builtin.command:
        cmd: >-
          tailscale cert
          --cert-file "/etc/pki/tls/private/{{ ansible_fqdn }}.crt"
          --key-file "/etc/pki/tls/private/{{ ansible_fqdn }}.key"
          "{{ ansible_fqdn }}"
        creates: "/etc/pki/tls/private/{{ ansible_fqdn }}.crt"

    - name: "allow caddy to use tailscale certificates"
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/default/tailscaled"
        line: "TS_PERMIT_CERT_UID=caddy"

    - name: "use tailscale certificates for cockpit"
      tags: [certificates]
      become: true
      ansible.builtin.file:
        src: "/etc/pki/tls/private/{{ ansible_fqdn }}.crt"
        dest: "/etc/cockpit/ws-certs.d/{{ ansible_fqdn }}.crt"
        state: link

    - name: "use tailscale certificates for cockpit"
      tags: [certificates]
      become: true
      ansible.builtin.file:
        src: "/etc/pki/tls/private/{{ ansible_fqdn }}.key"
        dest: "/etc/cockpit/ws-certs.d/{{ ansible_fqdn }}.key"
        state: link
