---
- tags: ['dnf', 'tailscale']
  become: true
  block:
    - name: 'add tailscale repository'
      ansible.builtin.yum_repository:
        name: 'tailscale'
        description: 'Tailscale stable'
        baseurl: 'https://pkgs.tailscale.com/stable/fedora/$basearch'
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: 'https://pkgs.tailscale.com/stable/fedora/repo.gpg'

    - name: 'install tailscale package'
      ansible.builtin.dnf:
        state: 'latest'
        pkg:
          - 'tailscale'
