"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$character$all$character"

[aws]
symbol = "aws "

[azure]
disabled = true

[bun]
disabled = true

[character]
success_symbol = "[\\$](purple)"
error_symbol = "[\\$](red)"

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[directory]
style = "blue"
read_only = " ro"
truncation_length = 99
truncate_to_repo = false

[directory.substitutions]
"~/Development/github.com/borntyping" = "~borntyping"
"~/Development/github.com/ovotech" = "~ovotech"
"~/Development/github.com" = "~github"
"~/Development/gitlab.com" = "~gitlab"
"~/Development/scratch" = "~scratch"
"~/Development" = "~source"

[docker_context]
symbol = "docker "

[elixir]
disabled = true

[elm]
disabled = true

[git_branch]
style = "purple"
format = "[$branch(:$remote_branch)]($style)"

[git_commit]
tag_symbol = " tag "

[git_status]
format = '( $all_status)( $ahead_behind) '
conflicted = "[=$count](red)"
ahead = "[↑$count](green)"
behind = "[↓$count](red)"
diverged = "[⇅](red)"
up_to_date = ""
untracked = "[-$count](red)"
stashed = "[\\$$count](cyan)"
modified = "[+$count](yellow)"
staged = "[+$count](green)"
renamed = "[»$count](yellow)"
deleted = "[-$count](yellow)"
style = ""

[golang]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[memory_usage]
symbol = "memory "

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
symbol = "nodejs "

[package]
symbol = "pkg "

[php]
symbol = "php "

[python]
detect_files = ["__init__.py", "pyproject.toml", "setup.py"]
format = 'via [${symbol}(${version} )]($style)'
python_binary = ["./venv/bin/python", "python", "python3"]
style = "#FFE873" # https://brandpalettes.com/python-logo-colors/
symbol = "python "
version_format = "$raw"

[ruby]
symbol = "ruby "

[rust]
symbol = "rust "

[scala]
disabled = true

[sudo]
symbol = "sudo "

[swift]
disabled = true

[terraform]
format = "via [$symbol]($style) "
symbol = "terraform "
style = "#844FBA" # https://www.hashicorp.com/brand

[zig]
disabled = true
