"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$character\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$golang\
$helm\
$java\
$nodejs\
$php\
$python\
$ruby\
$rust\
$scala\
$terraform\
$aws\
$azure\
$gcloud\
$kubernetes\
$openstack\
$sudo\
$cmd_duration\
$jobs\
$line_break\
$character"""

[character]
success_symbol = "[\\$](purple)"
error_symbol = "[\\$](red)"

[directory]
read_only = " ro"
style = "blue"
truncate_to_repo = false
truncation_length = 99

[directory.substitutions]
"~/Development/github.com/borntyping" = "~borntyping"
"~/Development/github.com/ovotech" = "~ovotech"
"~/Development/github.com" = "~github"
"~/Development/gitlab.com" = "~gitlab"
"~/Development/scratch" = "~scratch"
"~/Development" = "~source"

[git_branch]
style = "purple"
format = "[$branch(:$remote_branch)]($style)"

[git_commit]
tag_symbol = " tag "

[git_status]
format = '( $all_status)( $ahead_behind) '
conflicted = "[=$count](red)"
ahead = "[↑$count](green)"
behind = "[↓$count](red)"
diverged = "[⇅](red)"
up_to_date = ""
untracked = "[-$count](red)"
stashed = "[\\$$count](cyan)"
modified = "[+$count](#FFE873)"
staged = "[+$count](green)"
renamed = "[»$count](#FFE873)"
deleted = "[-$count](#FFE873)"
style = ""

[package]
symbol = "pkg"
style = ""

[golang]
symbol = "golang"
style = "#29BEB0"

[helm]
symbol = "helm"
style = "#326CE5"

[java]
symbol = "java"
style = "#F89820"

[nodejs]
symbol = "nodejs"
style = "#66CC33"

[php]
symbol = "php"
style = "#777BB3"

[python]
detect_files = ["__init__.py", "pyproject.toml", "setup.py"]
format = 'via [${symbol}(${version} )]($style)'
python_binary = ["./venv/bin/python", "python", "python3"]
style = "#FFE873"
symbol = "python "
version_format = "$raw"

[ruby]
symbol = "ruby"
style = "#CC0000"

[rust]
symbol = "rust"
style = "#F74C00"

[scala]
symbol = "scala"
style = "#DE3423"

[terraform]
format = "via [$symbol]($style) "
symbol = "terraform"
style = "#844FBA" # https://www.hashicorp.com/brand

[aws]
symbol = "aws"
style = "#FF9900"

[azure]
symbol = "azure"
style = "#008AD7"

[gcloud]
symbol = "gcloud"
style = ""

[kubernetes]
symbol = "kubernetes"
style = "#326ce5"

[openstack]
symbol = "openstack"
style = ""

[sudo]
symbol = "sudo"
style = "bold red"

[cmd_duration]
style = ""

[jobs]
format = "[\\[$number\\]]($style) "
style = "cyan"
number_threshold = 1
