---
- tags:
    - 'home'
    - 'dotfiles'
    - 'git'
  block:
    - name: 'copy git config directory'
      ansible.builtin.copy:
        src: '.config/git/'
        dest: '{{ ansible_user_dir }}/.config/git/'
        mode: 'preserve'

    - name: 'create git config.d files'
      ansible.builtin.copy:
        content: '{{ item.value }}'
        dest: '{{ ansible_user_dir }}/.config/git/config.d/{{ item.key }}'
        mode: 'preserve'
      loop: '{{ git_config|combine(git_config_local)|dict2items }}'
      loop_control:
        label: '{{ item.key }}'

    - name: 'create git hosts.d directories'
      ansible.builtin.file:
        name: '{{ ansible_user_dir }}/.config/git/hosts.d/{{ item }}'
        state: 'directory'
      loop: '{{ git_dirs + git_dirs_local }}'
      tags: focus

    - name: 'create git hosts.d files'
      ansible.builtin.copy:
        content: '{{ item.value }}'
        dest: '{{ ansible_user_dir }}/.config/git/hosts.d/{{ item.key }}'
        mode: 'preserve'
      loop: '{{ git_hosts|combine(git_hosts_local)|dict2items }}'
      loop_control:
        label: '{{ item.key }}'

    - name: 'assemble git config'
      ansible.builtin.assemble:
        src: '{{ ansible_user_dir }}/.config/git/config.d/'
        dest: '{{ ansible_user_dir }}/.config/git/config'
        delimiter: '\n'

    - name: 'create git source code directories'
      ansible.builtin.file:
        name: '{{ ansible_user_dir }}/Development/{{ item }}'
        state: 'directory'
      with_items: '{{ git_dirs + git_dirs_local }}'
