---
- tags:
    - 'home'
    - 'dotfiles'
    - 'git'
    - focus
  block:
    - name: 'update facts'
      ansible.builtin.set_fact:
        _git_forges: '{{ git_forges + git_forges_local + git_forges_secret }}'

    - name: 'copy git config directory'
      ansible.builtin.copy:
        src: '.config/git/'
        dest: '{{ ansible_user_dir }}/.config/git/'
        mode: 'preserve'

    - name: 'create git config.d files for includeIf config'
      ansible.builtin.copy:
        content: |
          [includeIf "gitdir:{{ item.path|default("~/Development/%s/%s/**" | format(item.host, item.user)) }}"]
          path = hosts.d/{{ item.host }}/{{ item.user }}.config
        dest: '{{ ansible_user_dir }}/.config/git/config.d/{{ item.priority|default(50) }}-{{ item.host }}-{{ item.user }}.config'
        mode: 'preserve'
      loop: '{{ _git_forges }}'
      loop_control:
        label: '{{ item.host }}/{{ item.user }}'

    - name: 'create git hosts.d directories'
      ansible.builtin.file:
        name: '{{ ansible_user_dir }}/.config/git/hosts.d/{{ item.host }}'
        state: 'directory'
      loop: '{{ _git_forges }}'
      loop_control:
        label: '{{ item.host }}/{{ item.user }}'

    - name: 'create git hosts.d files'
      ansible.builtin.template:
        src: 'host.config'
        dest: '{{ ansible_user_dir }}/.config/git/hosts.d/{{ item.host }}/{{ item.user }}.config'
        mode: 'preserve'
      loop: '{{ _git_forges }}'
      loop_control:
        label: '{{ item.host }}/{{ item.user }}'

    - name: 'assemble git config'
      ansible.builtin.assemble:
        src: '{{ ansible_user_dir }}/.config/git/config.d/'
        dest: '{{ ansible_user_dir }}/.config/git/config'
        delimiter: '\n'

    - name: 'create git source code directories for each host'
      ansible.builtin.file:
        name: '{{ ansible_user_dir }}/Development/{{ item }}'
        state: 'directory'
      loop: '{{ _git_forges|map(attribute="host")|unique }}'

    - name: 'create git source code directories for each host + user'
      ansible.builtin.file:
        name: '{{ ansible_user_dir }}/Development/{{ item.host }}/{{ item.user }}'
        state: 'directory'
      loop: '{{ _git_forges }}'
      loop_control:
        label: '{{ item.host }}/{{ item.user }}'
