#!/bin/bash

#
# ZSH options
#

SAVEHIST=10000                   # Lines of history to save to a file.
HISTSIZE=10000                   # Lines of history to keep in memory.
HISTFILE="$HOME/.zhistory"       # Save history.

setopt ALWAYS_TO_END             # Move cursor after completion.
setopt APPEND_HISTORY            # Append to $HISTFILE, not replace.
setopt AUTO_LIST                 # List choices on ambiguous completion.
setopt AUTO_MENU                 # Show completion menu on tab press.
setopt AUTO_NAME_DIRS            # Allows 'cd ~borntyping' (see below).
setopt AUTO_PARAM_KEYS           # Intelligent handling of characters
setopt AUTO_PARAM_SLASH          #   after a completion.
setopt AUTO_REMOVE_SLASH         # Remove trailing slash when needed.
setopt COMPLETE_ALIASES          # Allow autocompletion for aliases.
setopt COMPLETE_ALIASES          # Tab complete aliases.
setopt COMPLETE_IN_WORD          # Allow completion from middle of word
setopt EXTENDED_GLOB             # File modification glob modifiers.
setopt EXTENDED_HISTORY          # Record additional information.
setopt HIST_EXPIRE_DUPS_FIRST    # Remove duplicate entries first.
setopt HIST_FIND_NO_DUPS         # Never find duplicates when searching.
setopt HIST_IGNORE_ALL_DUPS      # Remove old duplicate entries first.
setopt HIST_IGNORE_DUPS          # Ignore adjacent repeated entries.
setopt HIST_IGNORE_SPACE         # Skip if the line starts with space.
setopt HIST_SAVE_NO_DUPS         # Never save duplicate commands.
setopt HIST_VERIFY               # Don't immediately run history commands.
setopt INC_APPEND_HISTORY        # Append to $HISTFILE while running.
setopt INTERACTIVE_COMMENTS      # Allow comments in interactive mode.
setopt LIST_PACKED               # Smallest completion menu.
setopt RM_STAR_WAIT              # Force the user to wait before 'rm *'.
setopt SHARE_HISTORY             # Share history between ZSH instances.
unsetopt FLOW_CONTROL            # Disable start/stop characters.
unsetopt MENU_COMPLETE           # Don't autoselect completions.

#
# Keybindings
#

# Shift-Tab to go back in menus.
# Ensure Home/End work as expected.
bindkey '^[[H' beginning-of-line # Home key returns to the start of the line.
bindkey '^[[F' end-of-line
bindkey '^[[Z' reverse-menu-complete

# Edit current line (Ctrl+e).
autoload edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line

#
# Aliases
#

alias cola='git-cola &'
alias gc='git commit'
alias gca='git commit -a'
alias gd='git diff'
alias grep='grep --color=auto'
alias gs='git status'
alias httpie='http'
alias k='kubectl'
alias la='ls -la'
alias ll='ls -l'
alias ls='ls --color=auto'
alias please='sudo'
alias reconfigure-ssh='reconfigure -t ssh --force-handlers'
alias reconfigure-zshrc='reconfigure -t zshrc; source ~/.zshrc'

#
# Named directories
#

export github="$HOME/Development/github.com"
export gitlab="$HOME/Development/gitlab.com"

export borntyping="${github}/borntyping"
export sandbox="${github}/borntyping-sandbox"

#
# Environment variables
#

export EDITOR="micro"
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
export FZF_DEFAULT_OPTS="--no-height --no-reverse"
export GIT_PATH="${dev}" # git-get
export GIT_WORKSPACE="$HOME/Development"
export GOPATH="$HOME/.local/lib/go"
export LS_COLORS="rs=0:di=01;33:ln=target:or=41:ex=32"
export NPM_CONFIG_PREFIX="$HOME/.npm"
export PAGER="bat"
export PATH="${HOME}/.bin:${PATH}:${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/.cargo/bin:${PATH}:${HOME}/.npm/bin:${PATH}"
export PATH="${HOME}/.krew/bin:$PATH"
export PIPENV_IGNORE_VIRTUALENVS=1
export PIPENV_MAX_DEPTH=5
export SSH_RUN_SUDO_KEYRING=1
export VIRTUAL_ENV_DISABLE_PROMPT=1
export ZSH_PECO_HISTORY_DEDUP=1

#
# ZSH packages using antigen.
# https://github.com/zsh-users/antigen
#

# shellcheck source=local/share/zsh/antigen.zsh
source "$HOME/.local/share/zsh/antigen.zsh"
antigen bundles <<EOBUNDLES
  ael-code/zsh-colored-man-pages
  agkozak/zsh-z
  zsh-users/zsh-completions
  zsh-users/zsh-syntax-highlighting
EOBUNDLES
antigen apply

#
# Completion rules
#

fpath=("$HOME/.local/share/zsh/functions" $fpath)
autoload -Uz compinit
zstyle ':completion::complete:*' cache-path "$HOME/.cache/zsh/completion/"
zstyle ':completion::complete:*' use-cache on
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*:*:*:users' ignored-patterns '*'
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
compinit -C

#
# ZSH syntax highlighting plugin (loaded by antigen).
# https://github.com/zsh-users/zsh-syntax-highlighting
#

export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
export ZSH_HIGHLIGHT_STYLES['comment']='fg=green'
export ZSH_HIGHLIGHT_STYLES['unknown-token']='fg=red'
export ZSH_HIGHLIGHT_STYLES['globbing']='fg=cyan'
export ZSH_HIGHLIGHT_STYLES['single-quoted-argument']='fg=blue'
export ZSH_HIGHLIGHT_STYLES['double-quoted-argument']='fg=blue'
export ZSH_HIGHLIGHT_STYLES['dollar-double-quoted-argument']='fg=yellow'
export ZSH_HIGHLIGHT_STYLES['back-double-quoted-argument']='fg=yellow'

#
# fzf keybindings
# https://github.com/junegunn/fzf/blob/master/shell/completion.zsh
#

[[ -f "/usr/share/doc/fzf/examples/key-bindings.zsh" ]] && source "/usr/share/doc/fzf/examples/key-bindings.zsh"
[[ -f "/usr/share/doc/fzf/examples/completion.zsh" ]] && source "/usr/share/doc/fzf/examples/completion.zsh"

#
# direnv - directory specific environment configuration
# https://direnv.net/
#

eval "$(direnv hook zsh)"

#
# Kubernetes completion
# https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion
#

source <(kubectl completion zsh)
source <(minikube completion zsh)

#
# Oreutils - must come after $PATH is set.
# https://github.com/Manishearth/oreutils
#

[[ -x "$(command -v ripgrep)" ]] && alias grep='ripgrep'
[[ -x "$(command -v exa)" ]] && alias ls='exa'
[[ -x "$(command -v fd)" ]] && alias find='fd'
[[ -x "$(command -v bat)" ]] && alias cat='bat'

#
# Kubernetes helpers
#

function ky() {
  kubectl -o yaml "$@" | bat --language yaml
}
function kq() {
  kubectl -o json "$@" | jq .
}

compdef k="kubectl"
compdef kq="kubectl"
compdef ky="kubectl"

#
# Personal "libaries" deployed by Ansible.
#

# ZSH prompt
# shellcheck source=local/share/zsh/prompt.zsh
source "$HOME/.local/share/zsh/prompt.zsh"

# Local zsh config
# shellcheck source=/home/sam/.local/share/zsh/prompt.zsh
[[ -f "$HOME/.config/zsh/zshrc" ]] && source "$HOME/.config/zsh/zshrc"

#
# Tilix VTE patch
# https://github.com/gnunn1/tilix/wiki/VTE-Configuration-Issue
#

[[ -f "/etc/profile.d/vte-2.91.sh" ]] && source "/etc/profile.d/vte-2.91.sh"
