#!/bin/zsh
# shellcheck disable=SC1090 disable=SC2034 disable=SC2206

HISTFILE="$HOME/.zhistory"              # Save history.
HISTSIZE=7500                           # Lines of history to keep in memory.
SAVEHIST=5000                           # Lines of history to save to a file.

setopt ALWAYS_TO_END                    # Move cursor after completion.
setopt APPEND_HISTORY                   # Append to $HISTFILE, not replace.
setopt AUTO_LIST                        # List choices on ambiguous completion.
setopt AUTO_MENU                        # Show completion menu on tab press.
setopt AUTO_NAME_DIRS                   # Allows 'cd ~borntyping' (see below).
setopt AUTO_PARAM_KEYS                  # Intelligent handling of characters
setopt AUTO_PARAM_SLASH                 #   after a completion.
setopt AUTO_REMOVE_SLASH                # Remove trailing slash when needed.
setopt COMPLETE_ALIASES                 # Allow autocompletion for aliases.
setopt COMPLETE_ALIASES                 # Tab complete aliases.
setopt COMPLETE_IN_WORD                 # Allow completion from middle of word
setopt EXTENDED_HISTORY                 # Record additional information.
setopt HIST_EXPIRE_DUPS_FIRST           # Remove duplicate entries first.
setopt HIST_FIND_NO_DUPS                # Never find duplicates when searching.
setopt HIST_IGNORE_ALL_DUPS             # Remove old duplicate entries first.
setopt HIST_IGNORE_DUPS                 # Ignore adjacent repeated entries.
setopt HIST_IGNORE_SPACE                # Skip if the line starts with space.
setopt HIST_SAVE_NO_DUPS                # Never save duplicate commands.
setopt HIST_VERIFY                      # Don't immediately run history commands.
setopt INC_APPEND_HISTORY               # Append to $HISTFILE while running.
setopt INTERACTIVE_COMMENTS             # Allow comments in interactive mode.
setopt LIST_PACKED                      # Smallest completion menu.
setopt RM_STAR_WAIT                     # Force the user to wait before 'rm *'.
setopt SHARE_HISTORY                    # Share history between ZSH instances.
unsetopt FLOW_CONTROL                   # Disable start/stop characters.
unsetopt MENU_COMPLETE                  # Don't autoselect completions.

autoload edit-command-line
zle -N edit-command-line

bindkey '\e[3~' delete-char             # Ensure Delete works as expected.
bindkey '^[[F' end-of-line              # Ensure End works as expected.
bindkey '^[[H' beginning-of-line        # Ensure Home works as expected.
bindkey '^[[Z' reverse-menu-complete    # Shift-Tab to go back in menus.
bindkey '^e' edit-command-line          # Edit current line (Ctrl+e).
bindkey -r "^V"                         # Disable `ctrl-v` so it does not mix with `ctrl-shift-v`.

alias cola='git-cola &'
alias d='docker run --rm -it $(docker build -q .)'
alias gc='git commit'
alias gca='git commit -a'
alias gd='git diff'
alias gitg='gitg &'
alias grep='grep --color=auto'
alias gs='git status'
alias httpie='http'
alias la='ls -la'
alias ll='ls -l'
alias ls='ls --color=auto'
alias reconfigure-zshrc='reconfigure -t zshrc; source ~/.zshrc'

export BAT_PAGER="less --quit-if-one-screen --RAW-CONTROL-CHARS --no-init"
export BAT_STYLE="plain"
export EDITOR="micro"
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
export FZF_DEFAULT_OPTS="--no-height --no-reverse"
export GIT_WORKSPACE="${HOME}/Development/git-workspace" # orf/git-workspace
export GITGET_ROOT="${HOME}/Development/git-get" # grdl/git-get
export GOPATH="${HOME}/.local/lib/go"
export LS_COLORS="rs=0:di=01;33:ln=target:or=41:ex=32"
export NPM_CONFIG_PREFIX="${HOME}/.npm"
export PAGER="bat"
export PATH="${HOME}/.bin:${HOME}/.local/bin:${HOME}/.local/share/src/:${PATH}"
export PATH="${HOME}/.cargo/bin:${HOME}/.npm/bin:${HOME}/.krew/bin:${PATH}"
export PIPENV_IGNORE_VIRTUALENVS=1
export PIPENV_MAX_DEPTH=5
export SSH_RUN_SUDO_KEYRING=1
export TERM="xterm-256color"
export VIRTUAL_ENV_DISABLE_PROMPT=1
export ZSH_PECO_HISTORY_DEDUP=1
export ZSHZ_DATA="${HOME}/.cache/zsh/z"
export ZSHZ_NO_RESOLVE_SYMLINKS=1

# 2.5.7: Named directories
# http://zsh.sourceforge.net/Guide/zshguide02.html
export borntyping="${GIT_WORKSPACE}/github.com/borntyping"
export github="${GIT_WORKSPACE}/github.com"
export gitlab="${GIT_WORKSPACE}/gitlab.com"
export source="${GITGET_ROOT}"
export scratch="${HOME}/Development/scratch"

# ZSH packages using antigen.
# https://github.com/zsh-users/antigen
source "$HOME/.local/share/zsh/antigen.zsh"
antigen bundles <<EOBUNDLES
  ael-code/zsh-colored-man-pages
  agkozak/zsh-z
  zsh-users/zsh-completions
  zsh-users/zsh-syntax-highlighting
EOBUNDLES
antigen apply

# Direnv
# https://direnv.net/
eval "$(direnv hook zsh)"

# Completion rules
# http://zsh.sourceforge.net/Doc/Release/Completion-System.html
fpath+=("${HOME}/.cache/zsh/functions")
autoload -Uz compinit
zstyle ':completion:*:*:*:*:*' menu select                                      # Select completions with an interactive menu.
#zstyle ':completion:*:*:*:users' ignored-patterns '*'
#zstyle ':completion:*' list-colors ''
#zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
compinit -C

# ZSH syntax highlighting plugin (loaded by antigen)
# https://github.com/zsh-users/zsh-syntax-highlighting
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
export ZSH_HIGHLIGHT_STYLES['comment']='fg=green'
export ZSH_HIGHLIGHT_STYLES['unknown-token']='fg=red'
export ZSH_HIGHLIGHT_STYLES['globbing']='fg=cyan'
export ZSH_HIGHLIGHT_STYLES['single-quoted-argument']='fg=blue'
export ZSH_HIGHLIGHT_STYLES['double-quoted-argument']='fg=blue'
export ZSH_HIGHLIGHT_STYLES['dollar-double-quoted-argument']='fg=yellow'
export ZSH_HIGHLIGHT_STYLES['back-double-quoted-argument']='fg=yellow'

# Replace various coreutils executables with oreutils alternatives.
[[ -x "$(command -v bat)" ]] && alias cat='bat'
[[ -x "$(command -v exa)" ]] && alias ls='exa'
[[ -x "$(command -v rg)" ]] && alias grep='rg'

# Support various utilities if available
[[ -f "/etc/profile.d/vte-2.91.sh" ]] && source "/etc/profile.d/vte-2.91.sh"    # Fix for Tilix.
[[ -f "/usr/share/fzf/shell/key-bindings.zsh" ]] && source "/usr/share/fzf/shell/key-bindings.zsh"
[[ -x "$(command -v oc)" ]] && source "$HOME/.cache/zsh/functions/_oc"          # The oc completion doesn't work with fpath.

# Machine-local configuration.
[[ -f "$HOME/.config/zsh/zshrc" ]] && source "$HOME/.config/zsh/zshrc"

# Load custom prompt
source "$HOME/.local/share/zsh/prompt.zsh"
