[[provider]]
provider = "github"
name = "borntyping"
path = "/home/sam/Development/github.com"
env_var = "GITHUB_TOKEN"
skip_forks = false

[[provider]]
provider = "gitlab"
name = "borntyping"
url = "https://gitlab.com"
path = "/home/sam/Development/gitlab.com"
env_var = "GITLAB_TOKEN"
