---
- tags: ['dnf', 'redhat', 'fedora']
  block:
    - name: 'add tailscale repository'
      become: true
      ansible.builtin.yum_repository:
        name: 'tailscale'
        description: 'Tailscale stable'
        baseurl: 'https://pkgs.tailscale.com/stable/fedora/$basearch'
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: 'https://pkgs.tailscale.com/stable/fedora/repo.gpg'

    - name: 'install dnf packages'
      tags: ['fzf', 'postgres']
      become: true
      ansible.builtin.dnf:
        state: 'latest'
        pkg:
          - 'ShellCheck'
          - 'ansible-core'
          - 'awscli2'
          - 'cargo'
          - 'clippy'
          - 'cockpit'
          - 'direnv'
          - 'docker-compose'
          - 'fzf'
          - 'gcc-c++'
          - 'git-delta'
          - 'golang'
          - 'httpie'
          - 'npm'
          - 'podman'
          - 'postgresql'
          - 'postgresql-server'
          - 'postgresql-upgrade'
          - 'python3'
          - 'python3-black'
          - 'python3-devel'
          - 'python3-flake8'
          - 'python3-mypy'
          - 'python3-pip'
          - 'python3-psycopg2'
          - 'python3-psycopg3'
          - 'python3-pytest'
          - 'python3.10'
          - 'python3.11'
          - 'python3.12'
          - 'python3.7'
          - 'python3.8'
          - 'python3.9'
          - 'rust-src'
          - 'rustc'
          - 'rustfmt'
          - 'snapd'
          - 'sqlite'
          - 'util-linux-user'
          - 'yamllint'
          - 'zsh-html'

    - name: 'remove dnf packages'
      become: true
      ansible.builtin.dnf:
        state: 'absent'
        pkg:
          - 'python3-poetry'
          - 'starship'
