---
- tags: ['dnf', 'redhat', 'fedora']
  block:
    - name: 'add tailscale repository'
      become: true
      ansible.builtin.yum_repository:
        name: 'tailscale'
        description: 'Tailscale stable'
        baseurl: 'https://pkgs.tailscale.com/stable/fedora/$basearch'
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: 'https://pkgs.tailscale.com/stable/fedora/repo.gpg'

    - name: 'install base packages with dnf'
      tags: ['fzf', 'postgres']
      become: true
      ansible.builtin.dnf:
        state: 'latest'
        pkg:
          - 'direnv'
          - 'fzf'
          - 'git-delta'
          - 'httpie'
          - 'zsh-html'

    - name: 'remove base packages with dnf'
      become: true
      ansible.builtin.dnf:
        state: 'absent'
        pkg:
          - 'python3-poetry'
          - 'starship'
