---
- tags: ['syncthing']
  block:
    - name: 'start and enable user services'
      tags: ['systemd']
      ansible.builtin.systemd_service:
        name: 'syncthing.service'
        scope: 'user'
        state: 'started'
        enabled: true

    - name: 'use tailscale certificates for syncthing'
      tags: ['certificates', 'tailscale']
      ansible.builtin.copy:
        remote_src: true
        src: '{{ tailscale_certificates_directory }}/{{ item.src }}'
        dest: '{{ ansible_user_dir }}/.local/state/syncthing/{{ item.dest }}'
      loop:
        - src: '{{ tailscale_host }}.crt'
          dest: 'https-cert.pem'
        - src: '{{ tailscale_host }}.key'
          dest: 'https-key.pem'
      notify:
        - 'syncthing'

    - name: 'listen for external requests (only use with ufw+tailscale!)'
      ansible.builtin.lineinfile:
        path: '{{ ansible_user_dir }}/.local/state/syncthing/config.xml'
        search_string: '        <address>127.0.0.1:8384</address>'
        line: '        <address>0.0.0.0:8384</address>'
      notify:
        - 'syncthing'
