---
- name: 'configure zsh'
  tags:
    - 'dotfiles'
    - 'shell'
    - 'zsh'
    - 'zshrc'
  block:
    - name: 'copy zsh libraries'
      ansible.builtin.copy:
        src: '.local/share/zsh/'
        dest: '{{ zsh_home }}/.local/share/zsh/'
        mode: 'u=rw,g=r,o=r'

    - name: 'copy zsh libraries'
      ansible.builtin.copy:
        src: '.local/share/src/'
        dest: '{{ zsh_home }}/.local/share/src/'
        mode: 'u=rw,g=r,o=r'

    - name: 'copy zsh config'
      ansible.builtin.copy:
        src: 'zshrc'
        dest: '{{ zsh_home }}/.zshrc'

    - name: 'create zsh directories'
      ansible.builtin.file:
        name: '{{ zsh_home }}/{{ item }}'
        state: 'directory'
      loop:
        - '.cache/zsh/'
        - '.cache/zsh/completion/'
        - '.cache/zsh/functions/'
        - '.config/zsh/'
        - '.config/zsh/zshrc.d/'

    # Stop .zshrc from crashing when zshrc.d is empty.
    - name: 'create empty zshrc.d file'
      tags: ['config', 'local']
      ansible.builtin.copy:
        content: ''
        dest: '{{ zsh_home }}/.config/zsh/zshrc.d/empty.zsh'

    - name: 'create zsh local configuration'
      tags: ['config', 'local']
      ansible.builtin.copy:
        content: '{{ item.value }}'
        dest: '{{ zsh_home }}/.config/zsh/zshrc.d/{{ item.key }}'
        mode: 'preserve'
      loop: '{{ zsh_zshrc|combine(zsh_zshrc_local)|dict2items }}'
      loop_control:
        label: '{{ item.key }}'

    - name: 'copy ~/.config/starship.toml'
      tags: ['starship']
      ansible.builtin.copy:
        src: '.config/starship.toml'
        dest: '{{ ansible_user_dir }}/.config/starship.toml'
