name             'system'
maintainer       'Sam Clements (borntyping)'
maintainer_email 'sam@borntyping.co.uk'
license          'MIT'
description      'Installs and configures system level packages'
version          '1.0.0'
