---
- import_tasks: 'tailscale.yml'
- tags: [web]
  block:
    # https://docs.docker.com/engine/install/fedora/
    - name: "add docker repository"
      tags: [dnf, docker]
      become: true
      command:
        cmd: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
        creates: "/etc/yum.repos.d/docker-ce.repo"

    - name: "install dnf packages"
      tags:
        - caddy
        - dnf
        - docker
        - podman
        - syncthing
        - systemd
      become: true
      ansible.builtin.dnf:
        state: latest
        pkg:
          - containerd.io
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - podman
          - podman-compose
          - podman-docker
          - podman-remote
          - syncthing

    - name: "remove dnf packages"
      tags: [dnf]
      become: true
      ansible.builtin.dnf:
        state: absent
        pkg:
          - caddy
          - postgresql-contrib
          - postgresql-server
          - python3-psycopg2
          - python3-psycopg3

    - name: "start and enable services"
      tags: [systemd]
      become: true
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        scope: user
        state: started
        enabled: true
      loop:
        - syncthing.service
        - docker.service

    - name: "stop and disable services"
      tags: [systemd]
      become: true
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
       - firewalld.service

    - name: "create docker mounts"
      become: true
      ansible.builtin.file:
        name: "/opt/{{ item }}"
        state: "directory"
        user: "{{ web_docker_mounts_owner }}"
        group: "{{ web_docker_mounts_owner }}"
        mode: "0770"
      with_items: "{{ web_docker_mounts }}"
