---
- tags:
    - web
    - tailscale
  block:
    - name: "create certificates for {{ web_domain }}"
      ansible.builtin.command:
        cmd: >-
          tailscale cert
          --cert-file "/etc/pki/tls/private/{{ web_domain }}.crt"
          --key-file "/etc/pki/tls/private/{{ web_domain }}.key"
          "{{ web_domain }}"
        creates: "/etc/pki/tls/private/{{ web_domain }}.crt"
      become: true

    - name: "allow caddy to use tailscale certificates"
      ansible.builtin.lineinfile:
        path: "/etc/default/tailscaled"
        line: "TS_PERMIT_CERT_UID=caddy"
      become: true
