---
- name: 'manage tailscale certificates'
  tags: ['base', 'tailscale', 'certificates']
  become: true
  block:
    - name: 'include os variables'
      include_vars: 'defaults/main.{{ ansible_os_family|lower }}.yml'

    - block:
        - name: 'check tailscale is logged in'
          ansible.builtin.command:
            cmd: >-
              tailscale status
          changed_when: false
      rescue:
        - name: 'tailscale is not logged in'
          fail:
            msg: 'run "sudo tailscale up --operator=$USER"'

    - name: 'check tailscale hostname ({{ tailscale_host }})'
      when: 'not tailscale_host.endswith(".ts.net")'
      fail:
        msg: 'tailscale_host is not set to a tailscale domain'

    - name: 'create certificates'
      ansible.builtin.command:
        cmd: >-
          tailscale cert
          --cert-file "{{ tailscale_certificates_directory }}/{{ tailscale_host }}.crt"
          --key-file "{{ tailscale_certificates_directory }}/{{ tailscale_host }}.key"
          "{{ tailscale_host }}"
        creates: '{{ tailscale_certificates_directory }}/{{ tailscale_host }}.crt'

    - name: 'create tailscale certificates group'
      ansible.builtin.group:
        name: '{{ tailscale_certificates_group }}'
        system: true
        state: 'present'

    - name: 'add the current user to the tailscale certificates group'
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        groups: '{{ tailscale_certificates_group }}'
        append: true

    - name: 'set permissions on certificate files'
      ansible.builtin.file:
        path: '{{ tailscale_certificates_directory }}/{{ item }}'
        owner: 'root'
        group: '{{ tailscale_certificates_group }}'
        mode: '0750'
      loop:
        - '{{ tailscale_host }}.crt'
        - '{{ tailscale_host }}.key'

#    - name: 'add caddy to the tailscale certificates group'
#      tags: ['caddy']
#      ansible.builtin.user:
#        name: 'caddy'
#        groups: '{{ tailscale_certificates_group }}'
#        append: true
#
#    - name: 'allow caddy to use tailscale certificates'
#      tags: ['caddy']
#      ansible.builtin.lineinfile:
#        path: '/etc/default/tailscaled'
#        line: 'TS_PERMIT_CERT_UID=caddy'
