---
- name: 'manage tailscale certificates'
  tags: ['base', 'tailscale', 'certificates']
  become: true
  block:
    - name: 'include os variables'
      tags: ['always']
      include_vars: 'defaults/main.{{ ansible_os_family|lower }}.yml'

    - name: 'start tailscale service'
      tags: ['systemd']
      ansible.builtin.systemd_service:
        name: 'tailscaled.service'
        state: 'started'
        enabled: true

    - block:
        - name: 'check tailscale is logged in'
          ansible.builtin.command:
            cmd: >-
              tailscale status
          changed_when: false
      rescue:
        - name: 'tailscale is not logged in'
          fail:
            msg: 'run "sudo tailscale up --operator=$USER"'

    - name: 'check tailscale hostname is defined'
      when: 'tailscale_host is undefined'
      fail:
        msg: 'tailscale_host is not defined, this is required for cockpit certificates'

    - name: 'check tailscale hostname'
      when: 'not tailscale_host.endswith(".ts.net")'
      fail:
        msg: 'tailscale_host is not set to a tailscale domain ({{ tailscale_host }})'

    - name: 'create certificates'
      ansible.builtin.command:
        cmd: >-
          tailscale cert
          --cert-file "{{ tailscale_certificates_directory }}/{{ tailscale_host }}.crt"
          --key-file "{{ tailscale_certificates_directory }}/{{ tailscale_host }}.key"
          "{{ tailscale_host }}"

    - name: 'create tailscale certificates group'
      ansible.builtin.group:
        name: '{{ tailscale_certificates_group }}'
        system: true
        state: 'present'

    - name: 'add the current user to the tailscale certificates group'
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        groups: '{{ tailscale_certificates_group }}'
        append: true

    - name: 'set permissions on certificate files'
      ansible.builtin.file:
        path: '{{ tailscale_certificates_directory }}/{{ item }}'
        owner: 'root'
        group: '{{ tailscale_certificates_group }}'
        mode: '0750'
      loop:
        - '{{ tailscale_host }}.crt'
        - '{{ tailscale_host }}.key'

    # https://tailscale.com/kb/1019/subnets?tab=linux#enable-ip-forwarding
    # echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
    # echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
    # sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
    - name: 'enable ipv4 forwarding'
      ansible.posix.sysctl:
        name: 'net.ipv4.ip_forward'
        value: '1'
        sysctl_file: '/etc/sysctl.d/90-tailscale.conf'
    - name: 'enable ipv6 forwarding'
      ansible.posix.sysctl:
        name: 'net.ipv6.conf.all.forwarding'
        value: '1'
        sysctl_file: '/etc/sysctl.d/90-tailscale.conf'

    # NETDEV=$(ip route show 8.8.8.8 | cut -f5 -d' ')
    # sudo ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off
    - name: 'optimise network performance'
      ansible.builtin.command:
        cmd: 'ethtool -K "{{ item }}" rx-udp-gro-forwarding on rx-gro-list off'
      loop: '{{ tailscale_ethtool_devices }}'


#    - name: 'add caddy to the tailscale certificates group'
#      tags: ['caddy']
#      ansible.builtin.user:
#        name: 'caddy'
#        groups: '{{ tailscale_certificates_group }}'
#        append: true
#
#    - name: 'allow caddy to use tailscale certificates'
#      tags: ['caddy']
#      ansible.builtin.lineinfile:
#        path: '/etc/default/tailscaled'
#        line: 'TS_PERMIT_CERT_UID=caddy'
