---
- name: 'foundryvtt-syncthing'
  become: true
  become_user: '{{ foundryvtt_user }}'
  ansible.builtin.systemd_service:
    name: 'syncthing'
    scope: 'user'
    daemon_reload: true
    state: 'restarted'
