#!/bin/zsh
# This hook is run after a new virtualenv is activated.

set -e

pip install --upgrade setuptools >/dev/null

echo -n "Installing testing and packaging tools..."
pip install tox pytest wheel twine >/dev/null
echo "done."
