#!/bin/bash

set -e

if [ "$(git config --get --bool hooks.rubocop)" != "false" ]; then
  if [[ "$(find -name '*.rb' | grep -v node_modules | wc -l)" -gt 0 ]]; then
    chef exec rubocop --format=clang
  fi
fi
