#!/bin/bash
#
# Automatically adds branch name and branch description to every commit message.
#

BRANCH=$(git symbolic-ref --short -q HEAD)

if [[ "$BRANCH" == *"feature/"* ]]; then
    NAME=$(echo "$BRANCH" | grep -Eo '[A-Z]+-[0-9]+')
    echo "[$NAME] $(cat "$1")" > "$1"
fi
