---
- tags:
    - 'docker'
    - 'sudo'
  block:
    - name: 'configure sudo'
      ansible.builtin.template:
        src: 'sudoers.j2'
        dest: '/etc/sudoers.d/{{ docker_user }}'
      become: true
      tags:
        - 'docker'
        - 'sudo'
        - 'sudoers'

    # Run "newgrp docker" to use the new group without logging out and back in.
    - name: 'add user to docker group'
      ansible.builtin.user:
        name: '{{ docker_user }}'
        groups: 'docker'
        append: true
      become: true
      tags:
        - 'docker'
