---
- tags:
    - 'base'
    - 'dnf'
  block:
    - name: 'add tailscale repository'
      become: true
      ansible.builtin.yum_repository:
        name: 'tailscale'
        description: 'Tailscale stable'
        baseurl: 'https://pkgs.tailscale.com/stable/fedora/$basearch'
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: 'https://pkgs.tailscale.com/stable/fedora/repo.gpg'

    - name: 'install dnf packages'
      become: true
      ansible.builtin.dnf:
        state: 'latest'
        pkg:
          - 'ShellCheck'
          - 'ack'
          - 'ansible-core'
          - 'asciinema'
          - 'awscli2'
          - 'bat'
          - 'cargo'
          - 'clippy'
          - 'colordiff'
          - 'curl'
          - 'direnv'
          - 'docker-compose'
          - 'exa'                       # ls replacement
          - 'fd-find'                   # find replacement
          - 'fish'
          - 'fzf'                       # shell menu
          - 'gcc-c++'                   # needed for cargo install task
          - 'gh'                        # github cli
          - 'git'
          - 'git-lfs'                   # git large file support
          - 'golang'                    # needed to install golang executables
          - 'htop'
          - 'jq'
          - 'micro'
          - 'nano'
          - 'npm'
          - 'pipx'                      # needed to install python executables
          - 'plantuml'
          - 'podman'                    # docker replacement
          - 'pre-commit'
          - 'python3'
          - 'python3-black'
          - 'python3-devel'
          - 'python3-flake8'
          - 'python3-mypy'
          - 'python3-pip'
          - 'python3-pytest'
          - 'python3.7'
          - 'python3.8'
          - 'python3.9'
          - 'python3.10'
          - 'python3.11'
          - 'python3.12'
          - 'ripgrep'                   # grep replacement
          - 'rust-src'
          - 'rustc'
          - 'rustfmt'
          - 'snapd'                     # needed to install snap dependencies
          - 'strace'
          - 'sqlite'
          - 'tailscale'
          - 'tree'
          - 'util-linux-user'
          - 'wl-clipboard'              # optional dependency of micro
          - 'zoxide'                    # provides z
          - 'zsh'
          - 'zsh-autosuggestions'
          - 'zsh-html'
          - 'zsh-syntax-highlighting'

    - name: 'remove dnf packages'
      become: true
      ansible.builtin.dnf:
        state: 'absent'
        pkg:
          - 'python3-poetry'
          - 'starship'
