---
- name: 'install dnf packages'
  import_tasks: 'packages_fedora.yml'
  when: 'ansible_distribution in ["Fedora"]'
  tags: ['dnf', 'package']

- name: 'install apt packages'
  import_tasks: 'packages_ubuntu.yml'
  when: 'ansible_distribution in ["Ubuntu"]'
  tags: ['apt', 'package']

- name: 'install generic packages'
  import_tasks: 'packages_generic.yml'
  when: 'ansible_distribution in ["Fedora", "Ubuntu"]'
  tags: ['apt', 'dnf', 'package']

- name: 'install snap packages'
  import_tasks: 'packages_snap.yml'
  when: 'ansible_distribution in ["Fedora", "Ubuntu"]'
  tags: ['snap', 'package']

- import_tasks: 'sudo.yml'
