---
- tags: ['base', 'apt']
  block:
    - name: 'add git ppa'
      become: true
      ansible.builtin.apt_repository:
        repo: 'ppa:git-core/ppa'

    - name: 'install apt packages'
      become: true
      ansible.builtin.apt:
        state: 'latest'
        pkg:
          - 'build-essential'
          - 'gcc'
          - 'python3'
          - 'python3-pip'

    - name: 'remove apt packages'
      become: true
      ansible.builtin.apt:
        state: 'absent'
        pkg:
          - 'ansible-core'
          - 'direnv'

- tags: ['base', 'homebrew']
  block:
    - name: 'check homebrew executable'
      stat:
        path: '/home/linuxbrew/.linuxbrew/bin/brew'
      register: 'homebrew_executable'
      check_mode: true

    - name: 'install homebrew packages'
      when: 'homebrew_executable.stat.exists'
      community.general.homebrew:
        state: present
        name:
          - 'go'
          - 'direnv'
