---
- tags:
    - 'base'
    - 'apt'
  block:
    - name: 'add git ppa'
      become: true
      ansible.builtin.apt_repository:
        repo: 'ppa:git-core/ppa'

    - name: 'install apt packages'
      become: true
      ansible.builtin.apt:
        state: 'latest'
        pkg:
          - 'build-essential'
          - 'gcc'
          - 'python3'
          - 'python3-pip'

    - name: 'remove apt packages'
      become: true
      ansible.builtin.apt:
        state: 'absent'
        pkg:
          - 'ansible-core'
