---
- tags:
    - 'base'
    - 'snap'
  block:
    # Enable 'classic' Snap support.
    # https://snapcraft.io/docs/installing-snap-on-fedora
    - name: 'configure snap'
      when: 'ansible_distribution == "Fedora"'
      become: true
      ansible.builtin.file:
        src: '/var/lib/snapd/snap'
        dest: '/snap'
        state: 'link'

    - name: 'install snap packages'
      become: true
      community.general.snap:
        name: '{{ item }}'
      loop:
        - 'lnav'
