---
- name: modify users
  user: >
    name='{{ item.key }}'
    comment='{{ item.value }}'
    generate_ssh_key=true
    groups=sudo
    append=true
  become: 'yes'
  with_dict: users

- name: create user www paths
  file: >
    path=/var/www/{{ item }}
    owner={{ item }}
    group={{ item }}
    state=directory
  become: 'yes'
  with_items: users.keys()

- include: site-borntyping.yml
  tags: ['sites', 'site-borntyping']
- include: site-eightbitgoggles.yml
  tags: ['sites', 'site-8bitgoggles']

- name: install nginx
  apt: pkg=nginx state=latest
  become: 'yes'
  tags:
    - nginx

- name: configure sites
  become: 'yes'
  template: >
    src=site-{{ item }}.conf
    dest=/etc/nginx/sites-available/{{ item }}.conf
    owner={{ nginx_sites[item].user }}
    group={{ nginx_sites[item].user }}
  with_items: nginx_sites.keys()
  register: nginx_config
  tags:
    - nginx

- name: enable sites
  become: 'yes'
  file: >
    src=/etc/nginx/sites-available/{{ item }}.conf
    dest=/etc/nginx/sites-enabled/{{ item }}.conf
    state=link
    force=yes
  with_items: nginx_sites.keys()
  register: nginx_enabled_sites
  tags:
    - nginx

- name: restart nginx
  when: nginx_config.changed or nginx_enabled_sites.changed
  service: name=nginx state=restarted
  become: 'yes'
  tags:
    - nginx
