#!/usr/bin/env zsh

set -e

function git_hook_enabled() {
    if [[ "$(git config --get --bool "hooks.$1")" != "false" ]]; then
        return 0
    else
        return 1
    fi
}

function git_hook_php() {
    if git_hook_enabled "$1" && [[ -f "vendor/bin/$1" ]]; then
        "vendor/bin/$1"
    fi
}

git_hook_php 'phpunit'
git_hook_php 'phpstan'
