---
- tags: ['base', 'cockpit']
  block:
    - name: 'use tailscale certificates for cockpit'
      tags: ['certificates', 'tailscale']
      become: true
      ansible.builtin.file:
        src: '{{ tailscale_certificates_directory }}/{{ item }}'
        dest: '/etc/cockpit/ws-certs.d/{{ item }}'
        state: 'link'
      loop:
        - '{{ tailscale_host }}.crt'
        - '{{ tailscale_host }}.key'
