---
- tags: ['dnf', 'redhat', 'fedora']
  block:
    - name: 'install dnf repositories'
      become: true
      ansible.builtin.copy:
        src: 'docker-ce.repo'
        dest: '/etc/yum.repos.d/docker-ce.repo'

    - name: 'install dnf packages'
      become: true
      ansible.builtin.dnf:
        state: 'latest'
        pkg:
          - 'containerd.io'
          - 'docker-buildx-plugin'
          - 'docker-ce'
          - 'docker-ce-cli'
          - 'docker-compose-plugin'
