---
- tags: apt
  block:
    - name: configure apt repository keys
      apt_key:
        id: '{{ item }}'
        keyserver: 'hkp://keyserver.ubuntu.com:80'
      register: apt_repositories_key
      become: 'yes'
      with_items:
        - '786285426B130F8C8C67CEF87F73D5BEFC1B6133'  # zeal
        - 'B9F8D658297AF3EFC18D5CDFA2F683C52980AECF'  # virtualbox

    - name: configure apt repositories
      apt_repository:
        repo: '{{ item }}'
        state: present
      register: apt_repositories
      become: 'yes'
      with_items:
        - 'deb http://ppa.launchpad.net/zeal-developers/ppa/ubuntu cosmic main'

    - name: update apt repositories
      apt:
        update_cache: 'yes'
      when: apt_repositories.changed or apt_repositories_key.changed
      become: 'yes'
