---
- tags:
    - 'stage3'
    - 'stage3-gui'
  block:
    - name: 'install packages'
      when: stage3_enabled
      ansible.builtin.apt:
        name:
          - 'firefox'
          - 'git-cola'
          - 'gitg'
          - 'meld'
          - 'tilix'
        state: 'latest'
      become: 'yes'

    - name: 'install .fonts/'
      copy:
        src: '.fonts/'
        dest: '{{ lookup("env", "HOME") }}/.fonts'
      tags:
        - 'config'
        - 'fonts'

    - name: 'install .config/tilix/'
      copy:
        src: '.config/tilix/'
        dest: '{{ lookup("env", "HOME") }}/.config/tilix'
      tags:
        - 'config'
        - 'tilix'
