---
- tags:
    - 'stage3'
    - 'stage3-gui'
  block:
    - name: 'install packages'
      ansible.builtin.dnf:
        name:
          - 'firefox'
          - 'git-cola'
          - 'gitg'
          - 'meld'
          - 'tilix'
        state: 'latest'
      become: 'yes'

    - name: 'install fonts'
      copy:
        src: 'fonts/'
        dest: '{{ lookup("env", "HOME") }}/.fonts'
      tags:
        - 'fonts'

#    - name: 'configure gnome alt-tab'
#      community.general.dconf:
#        key: '/org/gnome/shell/app-switcher/current-workspace-only'
#        value: 'true'
#        state: 'present'
