---
- tags:
    - 'stage3'
    - 'stage3-gui'
  block:
    - name: 'install packages'
      ansible.builtin.dnf:
        name:
          - 'firefox'
          - 'git-cola'
          - 'gitg'
          - 'gnome-shell-extension-dash-to-dock'
          - 'gnome-tweaks'
          - 'google-chrome-stable'
          - 'meld'
          - 'tilix'
          - 'zeal'
        state: 'latest'
      become: 'yes'
      tags:
        - 'dnf'

    - name: 'install 1Password'
      ansible.builtin.dnf:
        state: 'latest'
        pkg: 'https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm'
      become: 'yes'
      tags:
        - 'dnf'
        - '1p'

    - name: 'install snap packages'
      when: 'snap_enabled == true'
      community.general.snap:
        name: '{{ item }}'
      become: 'yes'
      loop:
        - 'slack'
      tags:
        - 'snap'

    - name: 'install snap packages with --clasic'
      when: 'snap_enabled == true'
      community.general.snap:
        name: '{{ item }}'
        classic: true
      become: 'yes'
      loop:
        - 'pycharm-professional'
      tags:
        - 'snap'

    - name: 'install .fonts/'
      copy:
        src: '.fonts/'
        dest: '{{ lookup("env", "HOME") }}/.fonts'
      tags:
        - 'config'
        - 'fonts'

    - name: 'install .config/tilix/'
      copy:
        src: '.config/tilix/'
        dest: '{{ lookup("env", "HOME") }}/.config/tilix'
      tags:
        - 'config'
        - 'tilix'
