---
#
# Install software only useful on a stage3-gui or non-headless machine.
#
- tags:
    - stage3
    - stage3-gui
  block:
    - import_tasks: apt.yml

    - name: install packages
      apt:
        pkg:
          - firefox
          - gparted
          - tilix
          - zeal
        state: latest
      become: 'yes'

    - name: install UI tools for Git
      apt:
        pkg:
          - git-cola
          - gitg
          - meld
        state: latest
      become: 'yes'

    - name: install fonts
      copy:
        src: 'fonts/'
        dest: '{{ ansible_env.HOME }}/.fonts'
      tags:
        - fonts
